# Usamos la imagen oficial de Nginx con Alpine
FROM nginx:alpine

# Copiamos el código del frontend (HTML, JS) al contenedor en el directorio de Nginx
COPY . /usr/share/nginx/html

# Exponemos el puerto 80 para que se pueda acceder a la aplicación web
EXPOSE 80
