services:
  
  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  
      MYSQL_DATABASE: backend           
     
    volumes:
      - db_data:/var/lib/mysql           
    networks:
      - dockerfinal_app-network 

  
  backend:
    build:
      context: ./backend  
    container_name: laravel-backend
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db           
      DB_PORT: 3306
      DB_DATABASE: backend
      DB_USERNAME: root
      DB_PASSWORD: ""       
    volumes:
      - ./backend:/var/www/html  
    depends_on:
      - db  
    networks:
      - dockerfinal_app-network
    ports:
      - "8000:8000"  

  frontend:
    build:
      context: ./js  
    container_name: frontend
    ports:
      - "3000:80"  
    networks:
      - dockerfinal_app-network  

volumes:
  db_data:

networks:
  dockerfinal_app-network:
    driver: bridge  
